// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSw95C9nwENo0IHaFpA9T4XxZs8xkx4oA',
    appId: '1:213678529677:web:0f56aedba5729c5bb8d6c4',
    messagingSenderId: '213678529677',
    projectId: 'myapp-55b6d',
    authDomain: 'myapp-55b6d.firebaseapp.com',
    storageBucket: 'myapp-55b6d.appspot.com',
    measurementId: 'G-42C7NZ2P1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUJ0XGBJc8GdrGxmaBn0PjnqmGf3MIeso',
    appId: '1:213678529677:android:63e0aacb32ee90b8b8d6c4',
    messagingSenderId: '213678529677',
    projectId: 'myapp-55b6d',
    storageBucket: 'myapp-55b6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzGpaZ32wSRWMs-R697G03aTrYW5U2pWQ',
    appId: '1:213678529677:ios:dad3d29793b8a493b8d6c4',
    messagingSenderId: '213678529677',
    projectId: 'myapp-55b6d',
    storageBucket: 'myapp-55b6d.appspot.com',
    iosBundleId: 'com.nareshptt.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzGpaZ32wSRWMs-R697G03aTrYW5U2pWQ',
    appId: '1:213678529677:ios:164cddf85eb484aab8d6c4',
    messagingSenderId: '213678529677',
    projectId: 'myapp-55b6d',
    storageBucket: 'myapp-55b6d.appspot.com',
    iosBundleId: 'com.example.flutterCrudOpration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSw95C9nwENo0IHaFpA9T4XxZs8xkx4oA',
    appId: '1:213678529677:web:292ed99ddc350e66b8d6c4',
    messagingSenderId: '213678529677',
    projectId: 'myapp-55b6d',
    authDomain: 'myapp-55b6d.firebaseapp.com',
    storageBucket: 'myapp-55b6d.appspot.com',
    measurementId: 'G-SLMHS0Q0D7',
  );
}
